#pragma once

// RogueCompany (4.24) SDK

#ifdef _MSC_VER
	#pragma pack(push, 0x8)
#endif

#include "../SDK.hpp"

namespace SDK
{
//---------------------------------------------------------------------------
//Parameters
//---------------------------------------------------------------------------

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.SwimNotifyTransitionStateLock
struct USub_Hero_ABP_Swimming_C_SwimNotifyTransitionStateLock_Params
{
	bool*                                              bpp__bShouldLock__pf;                                     // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.SwimNotifyTransitionEnd
struct USub_Hero_ABP_Swimming_C_SwimNotifyTransitionEnd_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.LocomotionStop
struct USub_Hero_ABP_Swimming_C_LocomotionStop_Params
{
	struct FVector*                                    bpp__StopLocation__pf;                                    // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.LocomotionStart
struct USub_Hero_ABP_Swimming_C_LocomotionStart_Params
{
	struct FVector*                                    bpp__StartLocation__pf;                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.LocomotionPivot
struct USub_Hero_ABP_Swimming_C_LocomotionPivot_Params
{
	struct FVector*                                    bpp__PivotLocation__pf;                                   // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EventStopSwimming
struct USub_Hero_ABP_Swimming_C_EventStopSwimming_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EventStartSwimming
struct USub_Hero_ABP_Swimming_C_EventStartSwimming_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EventDoGoDown
struct USub_Hero_ABP_Swimming_C_EventDoGoDown_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_EDD270D34439CCC54F7076BF79F86501
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_EDD270D34439CCC54F7076BF79F86501_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_E3E49F7F454B47E501D44EA073EE26EF
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_E3E49F7F454B47E501D44EA073EE26EF_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_CE2D32B1481E672703161D88E16C4293
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_CE2D32B1481E672703161D88E16C4293_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_C5D70A1F49036F86E187EE8C571CB2DC
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_C5D70A1F49036F86E187EE8C571CB2DC_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_C49A16B641148CF5EAC0AF962C213E99
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_C49A16B641148CF5EAC0AF962C213E99_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_C3BF42E04C99D31FBCA4D3AFC7973064
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_C3BF42E04C99D31FBCA4D3AFC7973064_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_C383F92B49670B60382C5A9FC1940F6D
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_C383F92B49670B60382C5A9FC1940F6D_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_C2D7D736421F594024F7C2AF55FCC2EE
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_C2D7D736421F594024F7C2AF55FCC2EE_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_BD5472394057FF2F92436AB44DC691B1
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_BD5472394057FF2F92436AB44DC691B1_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_BA9EF61A495651544A5BA4AFFA755093
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_BA9EF61A495651544A5BA4AFFA755093_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_B223D50A4F3B4C41684F9E8177A8F7A1
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_B223D50A4F3B4C41684F9E8177A8F7A1_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_AFB0DB7640628CC60CE90A88F7D7B406
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_AFB0DB7640628CC60CE90A88F7D7B406_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_9B29AAAF44C7BC37AE81E2A03FB98EE0
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_9B29AAAF44C7BC37AE81E2A03FB98EE0_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_938C84254015E9783201E49BF3DF9465
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_938C84254015E9783201E49BF3DF9465_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_6365BFCC4C7591A5B093198C5CA9FF8D
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_6365BFCC4C7591A5B093198C5CA9FF8D_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_5B8DBD004F9A9F51037D04B9CB4BB5D6
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_5B8DBD004F9A9F51037D04B9CB4BB5D6_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_412E9E2342DC09D338E7689E4AE3F409
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_412E9E2342DC09D338E7689E4AE3F409_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_35CE07414E66C5731CDC05BDE1C3FF54
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_35CE07414E66C5731CDC05BDE1C3FF54_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_2208B5994E350E2087383187EF43E431
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_2208B5994E350E2087383187EF43E431_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_131305F54923CBAAD2ECACAF3945B3DC
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_131305F54923CBAAD2ECACAF3945B3DC_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_10CC17F94E9FC40609685BA8E8696FD5
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_10CC17F94E9FC40609685BA8E8696FD5_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_0A8F60B345D2BCC08EA3789A0068E76B
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_0A8F60B345D2BCC08EA3789A0068E76B_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_069CC5CC44770AEB005A73A9D24ABCB8
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_069CC5CC44770AEB005A73A9D24ABCB8_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_01DF78A64F399D3147CEBFB5A62CE2E1
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_TransitionResult_01DF78A64F399D3147CEBFB5A62CE2E1_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendSpaceSkinned_D851DFDC483F78D4EAA22B93237B96A2
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendSpaceSkinned_D851DFDC483F78D4EAA22B93237B96A2_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendSpaceSkinned_7A7AB61949D5571EC30570B52C4D42BF
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendSpaceSkinned_7A7AB61949D5571EC30570B52C4D42BF_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendSpaceSkinned_41A40DD044D9659BD6A16D80547254CF
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendSpaceSkinned_41A40DD044D9659BD6A16D80547254CF_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendSpacePlayer_C4FB8F814F606919DFCCC893012E97E5
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendSpacePlayer_C4FB8F814F606919DFCCC893012E97E5_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendSpacePlayer_853E42D84AFC62678C3DDC898DF2A596
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendSpacePlayer_853E42D84AFC62678C3DDC898DF2A596_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendSpacePlayer_2C181114494B887D79B62E9850F50428
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendSpacePlayer_2C181114494B887D79B62E9850F50428_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendListByInt_DAF14B4B4B8333FABBF358A49999E8D3
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendListByInt_DAF14B4B4B8333FABBF358A49999E8D3_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendListByInt_9E589FC04A148FF3686CC28EC92AE41E
struct USub_Hero_ABP_Swimming_C_EvaluateGraphExposedInputs_ExecuteUbergraph_Sub_Hero_ABP_Swimming_AnimGraphNode_BlendListByInt_9E589FC04A148FF3686CC28EC92AE41E_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.BlueprintUpdateAnimation
struct USub_Hero_ABP_Swimming_C_BlueprintUpdateAnimation_Params
{
	float*                                             bpp__DeltaTimeX__pf;                                      // (Parm, ZeroConstructor, IsPlainOldData)
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.BlueprintInitializeAnimation
struct USub_Hero_ABP_Swimming_C_BlueprintInitializeAnimation_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.AnimNotify_UnLockTransitions
struct USub_Hero_ABP_Swimming_C_AnimNotify_UnLockTransitions_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.AnimNotify_PivotTransitionEnd
struct USub_Hero_ABP_Swimming_C_AnimNotify_PivotTransitionEnd_Params
{
};

// Function Sub_Hero_ABP_Swimming.Sub_Hero_ABP_Swimming_C.AnimGraph
struct USub_Hero_ABP_Swimming_C_AnimGraph_Params
{
	struct FPoseLink                                   bpp__AnimGraph__pf;                                       // (Parm, OutParm)
};

}

#ifdef _MSC_VER
	#pragma pack(pop)
#endif
